services:
  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_DB: coindb
      POSTGRES_PASSWORD: manager0
      POSTGRES_USER: manager
      TZ: "Asia/Seoul"
    ports:
      - 5432:5432
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
